---
dependencies:
- name: "alfresco-identity-service"
  repository: "https://kubernetes-charts.alfresco.com/incubator"
  version: "1.1.2"
- name: "common"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "1.1.35"
