apiVersion: v1
description: A Helm chart for Activiti Cloud Full Example
icon: https://raw.githubusercontent.com/Activiti/activiti.github.io/master/mstile-150x150.png
name: activiti-cloud-full-example
version: 7.12.0-rc.69
kubeVersion: '>=1.15.0-0'
sources:
  - https://github.com/Activiti/activiti-cloud-full-chart
