---
dependencies:
- name: "activiti-cloud-identity"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "0.0.7"
- name: "activiti-keycloak"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "0.0.31"
  condition: "infrastructure.activiti-keycloak.enabled,activiti-keycloak.enabled"
- name: "activiti-cloud-gateway"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "7.1.17"
  condition: "infrastructure.activiti-cloud-gateway.enabled,activiti-cloud-gateway.enabled"
- name: "activiti-cloud-query"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "7.1.117"
  condition: "application.activiti-cloud-query.enabled,activiti-cloud-query.enabled"
- name: "activiti-cloud-audit"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "7.1.123"
  condition: "application.activiti-cloud-audit.enabled,activiti-cloud-audit.enabled"
- name: "rabbitmq-ha"
  repository: "https://kubernetes-charts.storage.googleapis.com"
  version: "1.19.0"
  condition: "application.rabbitmq.enabled,rabbitmq.enabled"
  alias: "rabbitmq"
- name: "postgresql"
  repository: "https://kubernetes-charts.storage.googleapis.com"
  version: "3.11.3"
  condition: "application.postgres.enabled,postgres.enabled"
  alias: "postgres"
- name: "runtime-bundle"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "7.1.152"
  condition: "application.runtime-bundle.enabled,runtime-bundle.enabled"
- name: "activiti-cloud-connector"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "7.1.133"
  condition: "application.activiti-cloud-connector.enabled,activiti-cloud-connector.enabled"
- name: "activiti-cloud-notifications-graphql"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "7.1.118"
  condition: "application.activiti-cloud-notifications-graphql.enabled,activiti-cloud-notifications-graphql.enabled"
- name: "activiti-cloud-modeling"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "7.1.246"
  condition: "activiti-cloud-modeling.enabled,modeling.enabled"
